name: Swift

on: [push]
   schedule:
     - cron: "30 17 * * 0-6" # 17:30 every day of the week
jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
